#+OPTIONS: toc:nil
#+LATEX_HEADER: \usepackage[margin=1.25in]{geometry} \usepackage{booktabs} \usepackage{graphicx} \usepackage{adjustbox} \usepackage{amsmath} \usepackage{amsthm} \newtheorem{definition}{Definition} \usepackage{bookmark}
\begin{titlepage}
\centering
\includegraphics[width=0.15\textwidth]{example-image-1x1}\par\vspace{1cm}
{\scshape\LARGE Kungliga Tekniska Högskolan \par}
\vspace{1cm}
{\scshape\Large SF2930 Regression Analysis \par}
\vspace{1.5cm}
{\huge\bfseries Report II \\  \par}
\vspace{2cm}
{\Large\itshape Isac Karlsson \\ Ludvig Wärnberg Gerdin}
\vfill
Examiner \par
\textsc{Tatjana Pavlenko}

\vfill

{\large \today\par}
\end{titlepage}
# Page break
\newpage
\tableofcontents
\newpage

* Introduction
** Background
  Most of the tractors in Sweden have a third party liability insurance, because they are required by law. 
  In southern Europe a few large players have dominated the sales of tractor insurances. Our main task this
  project is to create our own tractor tariff on the form:
  
  \begin{equation}
    \text{Price} = \gamma_0 \prod_{k = 1}^M \gamma_{k,i}	
  \end{equation}

  Here y0 corresponds to the base level and yki are the risk factors and corresponds to each individual 
  tractor. 

** Data

   If P&C have provided us with data to train this price model, example given in the table below.

** Problem description
*** Risk Differentiation and Grouping

    Using GLM analysis we aim to make each group “Risk homogeneous” and that they contain enough data to
    get a stable GLM analysis, meanwhile handling imperfections in the dataset.

*** Levelling

    Here we aim to calculate yo such that the forecasted claim costs for each insurance are covered by the
    the price for each insurance, on a full year basis. We us a ratio between the estimated claim cost and
    the total premium of 90%. Lastly we calculate the base level yo from the formula given in (1).

* Methods
** Grouping and Risk Differentiation

   The criteria on which we based our groups were that

   1) Each group should be risk homogeneous, and
   2) Each group should have enough data to make the GLM estimates stable.
   Greater emphasis were placed on fulfilling criteria 2) due to it being more concrete.
   In order to do that we considered cut-offs that placed a fairly equal shares of data in 
   each risk group. 

   The resulting cut-offs and risk groups are found in section [[Results]].
   
*** Levelling

    Firstly, we subset the data rows (or customers) that had a \texttt{RiskYear} 2016. That 
    way the GLM analysis were only conducted on the active customers. not those that weren't
    customers to If anymore. From the aggregated data, initialized as \texttt{glmdata2} in the
    provided script, we calculated the yearly claim-cost per tractor by dividing the summed duration
    in each duration by the corresponding summed claim cost in


    In pseudo-code, the process was 

    #+begin_src R
    for each 
    #+end_src
* Results
* Conclusion
